import { describe, test, expect } from 'vitest';
import { isEmailish, normaliseEmail, emailError, EMAIL_MAX } from './email';

/**
 * The client check, and the one property that matters most about it.
 *
 * THE INVARIANT: anything the SERVER accepts, this must accept. A
 * client rule that rejects a legitimate address is worse than no rule
 * at all — it makes that address un-enterable with no way to appeal.
 * A missing check merely wastes a derivation.
 *
 * The corpus below is not invented. It was generated by running every
 * case against the server's real schema — zod 4.4.3,
 * z.string().email().max(254) — and recording the verdict: 124 cases,
 * 101 of which the server accepts, 0 violations. zod is a Server
 * dependency and deliberately not installed in Web, so the verdict is
 * pinned here rather than re-derived. If the server's rule is ever
 * loosened, this list is what needs regenerating.
 */

/** Addresses the server ACCEPTS. Every one must pass here too. */
const SERVER_ACCEPTS = [
  'a@b.co',
  'ab@example.com',
  'a.b@example.com',
  'a+tag@example.com',
  'a_b@c.io',
  'a-b@example.com',
  "o'brien@example.com",
  'A1@B.CO',
  'UPPER@EXAMPLE.COM',
  'user.name@example.co.uk',
  'demo-3a5aa1bcfae2c423cb17@demo.invalid',
  'a@sub.domain.example.com',
  'a@b.museum',
  'a@a-b.io',
  'a@b.c.d.e.f.gh',
  'a@b-.com',
  `${'x'.repeat(60)}@example.com`,
  `${'x'.repeat(240)}@b.co`
];

/** Addresses the server REJECTS, and which this catches before deriving. */
const SERVER_REJECTS_AND_SO_DO_WE = [
  'x',
  'a@b',
  'a@b.c',
  '@b.com',
  'a@',
  'a@.com',
  'a@b.',
  'a b@c.com',
  'a@b .com',
  `${'x'.repeat(300)}@b.com`
];

describe('the invariant: never stricter than the server', () => {
  test.each(SERVER_ACCEPTS)('accepts %s, because the server does', (address) => {
    expect(isEmailish(address)).toBe(true);
    expect(emailError(address)).toBe('');
  });
});

describe('what it catches before a derivation runs', () => {
  test.each(SERVER_REJECTS_AND_SO_DO_WE)('rejects %s', (address) => {
    expect(isEmailish(address)).toBe(false);
    expect(emailError(address)).not.toBe('');
  });

  test('"x" — the case from the survey — is rejected', () => {
    expect(isEmailish('x')).toBe(false);
    expect(emailError('x')).toBe('That does not look like an email address.');
  });
});

describe('cases left deliberately to the server', () => {
  // These are all rejected server-side. Mirroring the regex's exact
  // position on them would couple the two rules for no benefit, and
  // being wrong in the strict direction is the expensive mistake — so
  // they pass here and come back as VALIDATION_FAILED, which now has
  // human copy of its own.
  test.each([
    'a@b..com',
    '.a@b.com',
    '"q"@b.com',
    'a@-b.com',
    'ünicode@example.com',
    'a@münchen.de'
  ])('%s is left for the server to refuse', (address) => {
    expect(isEmailish(address)).toBe(true);
  });
});

describe('trimming', () => {
  test('surrounding whitespace is removed', () => {
    expect(normaliseEmail('  a@b.com  ')).toBe('a@b.com');
    expect(normaliseEmail(' a@b.com')).toBe('a@b.com');
    expect(normaliseEmail('a@b.com ')).toBe('a@b.com');
  });

  test('an untrimmed address is accepted, because it is trimmed first', () => {
    // The server's regex is anchored, so " a@b.com" fails it — that
    // used to cost a full Argon2id derivation and come back as
    // VALIDATION_FAILED for an address the person can see is fine.
    expect(isEmailish(' a@b.com')).toBe(true);
    expect(emailError(' a@b.com')).toBe('');
  });

  test('case is NOT folded', () => {
    // The local part is case-sensitive by spec and the server stores
    // what it is given. Folding here would create accounts the server
    // sees as different from a differently-cased sign-in.
    expect(normaliseEmail('  UPPER@Example.COM ')).toBe('UPPER@Example.COM');
  });

  test('null and undefined are handled', () => {
    expect(normaliseEmail(null)).toBe('');
    expect(normaliseEmail(undefined)).toBe('');
  });
});

describe('length', () => {
  test('the bound is the server\'s own', () => {
    expect(EMAIL_MAX).toBe(254);
  });

  test('254 characters is accepted, 255 is not', () => {
    const at = '@b.co';                       // 5 characters
    const ok = 'x'.repeat(254 - at.length) + at;
    const tooLong = 'x'.repeat(255 - at.length) + at;

    expect(ok).toHaveLength(254);
    expect(isEmailish(ok)).toBe(true);
    expect(isEmailish(tooLong)).toBe(false);
  });

  test('a 300-character address says how long it is', () => {
    const long = 'x'.repeat(295) + '@b.co';
    expect(emailError(long)).toContain('300 characters');
    expect(emailError(long)).toContain('254');
  });
});

describe('an empty field is not an error', () => {
  test('nothing typed yet says nothing', () => {
    // The screens have their own "enter your email" message, and
    // flagging an untouched field on blur is nagging, not helping.
    expect(isEmailish('')).toBe(true);
    expect(emailError('')).toBe('');
    expect(emailError('   ')).toBe('');
  });
});
