/**
 * Generates cryptographic test vectors from the Node implementation.
 *
 * The browser port must reproduce these byte for byte. Without fixed
 * vectors, a subtle mismatch (a different HKDF info string, a wrong
 * salt encoding) produces a vault that one implementation can write
 * and the other cannot read — and the symptom is just "decryption
 * fails", with no indication of where.
 */
const fs = require('fs');
const path = require('path');

const {
  deriveKeys, encryptItem, decryptItem,
  wrapDEK, unwrapDEK, deriveRecoveryKek
} = require('../src/crypto');

// Everything fixed. No randomness anywhere in the inputs.
const PASSWORD = 'correct horse battery staple';
const SALT_HEX = '0123456789abcdef0123456789abcdef';
const KDF_PARAMS = { m: 19456, t: 2, p: 1 };

const DEK_HEX = 'a'.repeat(64);                    // 32 bytes of 0xaa
const KEK_NONCE_HEX = '000102030405060708090a0b';  // 12 bytes
const ITEM_NONCE_HEX = '0b0a09080706050403020100';

const RECOVERY_KEY = 'A3F9-K2M8-QR47-TVWX-YZ01-2345-6789-ABCD';
const RECOVERY_SALT_HEX = 'fedcba9876543210fedcba9876543210';

const ITEM = { site: 'github.com', username: 'me@example.com', password: 'hunter2' };

async function main() {
  const salt = Buffer.from(SALT_HEX, 'hex');
  const { authHash, kek } = await deriveKeys(PASSWORD, salt, KDF_PARAMS);

  const dek = Buffer.from(DEK_HEX, 'hex');
  const recoverySalt = Buffer.from(RECOVERY_SALT_HEX, 'hex');
  const recoveryKek = deriveRecoveryKek(RECOVERY_KEY, recoverySalt);

  // Encryption uses random nonces, so for reproducible vectors we
  // encrypt once here and record the result. The browser side verifies
  // by DECRYPTING these, which is deterministic.
  const wrappedDek = wrapDEK(dek, kek);
  const encryptedItem = encryptItem(ITEM, dek);
  const recoveryWrapped = wrapDEK(dek, recoveryKek);

  const vectors = {
    _comment: 'Generated by scripts/generate-vectors.js. The browser implementation must reproduce these exactly.',

    kdf: {
      password: PASSWORD,
      saltHex: SALT_HEX,
      params: KDF_PARAMS,
      expected: {
        authHashHex: authHash.toString('hex'),
        kekHex: kek.toString('hex')
      }
    },

    recovery: {
      recoveryKey: RECOVERY_KEY,
      saltHex: RECOVERY_SALT_HEX,
      expected: {
        recoveryKekHex: recoveryKek.toString('hex')
      }
    },

    // Decrypt these with the given keys and check you get the plaintext back.
    decryption: {
      dekHex: DEK_HEX,
      wrappedDek,
      encryptedItem,
      recoveryWrapped,
      expectedItem: ITEM
    }
  };

  const outPath = path.join(__dirname, '..', 'test', 'vectors', 'crypto-vectors.json');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(vectors, null, 2));

  // The browser suite reads its own copy, so write both. A manual
  // copy step gets forgotten, and then the test that exists to prove
  // the two implementations agree is comparing against a stale
  // snapshot instead — which defeats the whole point of having it.
  const webPath = path.join(
    __dirname, '..', '..', 'Web', 'src', 'crypto', 'vectors', 'crypto-vectors.json'
  );
  fs.writeFileSync(webPath, JSON.stringify(vectors, null, 2));

  // Sanity check: our own implementation must satisfy its own vectors.
  const roundTripped = decryptItem(encryptedItem, dek);
  if (JSON.stringify(roundTripped) !== JSON.stringify(ITEM)) {
    throw new Error('self-check failed: item did not round-trip');
  }
  if (!unwrapDEK(wrappedDek, kek).equals(dek)) {
    throw new Error('self-check failed: DEK did not unwrap');
  }

  console.log('Vectors written to', outPath);
  console.log('  authHash:', authHash.toString('hex').slice(0, 32) + '...');
  console.log('  kek     :', kek.toString('hex').slice(0, 32) + '...');
  console.log('Vectors written to', webPath);
}

main().catch(err => { console.error(err); process.exit(1); });